name: zip

on:
  push:
    branches:
      - main #2020年10月后github新建仓库默认分支改为main，注意更改

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: main #2020年10月后github新建仓库默认分支改为main，注意更改

    - name: Down
      run: |
        wget https://cdn.jsdelivr.net/npm/notyf@3/notyf.min.css
        wget https://raw.githubusercontent.com/thun888/myblog/gh-page/css/main.css
        wget https://raw.githubusercontent.com/thun888/myblog/gh-page/morecss/main.css -O morecss.css
        
    - name: Generate # 生成
      run: |
        mkdir public
        cat main.css morecss.css notyf.min.css > ./public/allin.css
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_branch: asstes
        publish_dir: ./public
